# Generated by Django 5.1.3 on 2024-11-30 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialdata',
            name='CompanyID',
            field=models.ForeignKey(db_column='CompanyID', on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to='myapp.company'),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='MetricID',
            field=models.ForeignKey(db_column='MetricID', on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to='myapp.metric'),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='StatementTypeID',
            field=models.ForeignKey(db_column='StatementTypeID', on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to='myapp.statementtype'),
        ),
        migrations.AlterField(
            model_name='financialdata',
            name='TimePeriodID',
            field=models.ForeignKey(db_column='TimePeriodID', on_delete=django.db.models.deletion.CASCADE, related_name='financial_data', to='myapp.timeperiod'),
        ),
    ]
