# Generated by Django 5.1.3 on 2024-12-23 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_alter_financialdata_companyid_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="financialdata",
            name="Valuation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
